version: '3'

volumes:
    sock:
    redis:

services:
    nginx:
        image: nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static:/static
            - sock:/sock
        ports:
            - "80:80"

    app:
        command: gunicorn --preload --bind=unix:/sock/app.sock --workers=6 wsgi
        restart: always
        image: open-rank-tracker
        build: .
        env_file:
            - variables.env
        volumes:
            - ./:/usr/src/app
            - sock:/sock

    app-background:
        command: python tasks.py worker -B --loglevel=info
        restart: always
        image: open-rank-tracker
        build: .
        env_file:
            - variables.env
        volumes:
            - ./:/usr/src/app
            - /var/run/docker.sock:/var/run/docker.sock

    redis:
        image: redis:5.0.4-stretch
        volumes:
            - redis:/data

    database:
        image: postgres
        restart: always
        volumes:
            - /var/lib/postgres:/var/lib/postgres
        expose:
            - 5432
        env_file:
            - variables.env
